<?php

/*
 *
 *  ____            _        _   __  __ _                  __  __ ____
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 *
 *
 */

declare(strict_types=1);

namespace pocketmine;

/**
 * @internal
 * Constants for all properties available in pocketmine.yml.
 * This is generated by build/generate-pocketmine-yml-property-consts.php.
 * Do not edit this file manually.
 */
final class YmlServerProperties{

	private function __construct(){
		//NOOP
	}

	public const CHUNK_GENERATION = 'chunk-generation';
	public const CHUNK_GENERATION_POPULATION_QUEUE_SIZE = 'chunk-generation.population-queue-size';
	public const CHUNK_SENDING = 'chunk-sending';
	public const CHUNK_SENDING_PER_TICK = 'chunk-sending.per-tick';
	public const CHUNK_SENDING_SPAWN_RADIUS = 'chunk-sending.spawn-radius';
	public const CHUNK_TICKING = 'chunk-ticking';
	public const CHUNK_TICKING_BLOCKS_PER_SUBCHUNK_PER_TICK = 'chunk-ticking.blocks-per-subchunk-per-tick';
	public const CHUNK_TICKING_DISABLE_BLOCK_TICKING = 'chunk-ticking.disable-block-ticking';
	public const CHUNK_TICKING_TICK_RADIUS = 'chunk-ticking.tick-radius';
	public const DEBUG = 'debug';
	public const MEMORY = 'memory';
	public const MEMORY_ASYNC_WORKER_HARD_LIMIT = 'memory.async-worker-hard-limit';
	public const MEMORY_CHECK_RATE = 'memory.check-rate';
	public const MEMORY_CONTINUOUS_TRIGGER = 'memory.continuous-trigger';
	public const MEMORY_CONTINUOUS_TRIGGER_RATE = 'memory.continuous-trigger-rate';
	public const MEMORY_GLOBAL_LIMIT = 'memory.global-limit';
	public const MEMORY_MAIN_HARD_LIMIT = 'memory.main-hard-limit';
	public const MEMORY_MAIN_LIMIT = 'memory.main-limit';
	public const MEMORY_MAX_CHUNKS = 'memory.max-chunks';
	public const MEMORY_MAX_CHUNKS_CHUNK_RADIUS = 'memory.max-chunks.chunk-radius';
	public const MEMORY_MEMORY_DUMP = 'memory.memory-dump';
	public const MEMORY_MEMORY_DUMP_DUMP_ASYNC_WORKER = 'memory.memory-dump.dump-async-worker';
	public const NETWORK = 'network';
	public const NETWORK_ASYNC_COMPRESSION = 'network.async-compression';
	public const NETWORK_ASYNC_COMPRESSION_THRESHOLD = 'network.async-compression-threshold';
	public const NETWORK_BATCH_THRESHOLD = 'network.batch-threshold';
	public const NETWORK_COMPRESSION_LEVEL = 'network.compression-level';
	public const NETWORK_ENABLE_ENCRYPTION = 'network.enable-encryption';
	public const NETWORK_MAX_MTU_SIZE = 'network.max-mtu-size';
	public const NETWORK_UPNP_FORWARDING = 'network.upnp-forwarding';
	public const PLAYER = 'player';
	public const PLAYER_SAVE_PLAYER_DATA = 'player.save-player-data';
	public const PLAYER_VERIFY_XUID = 'player.verify-xuid';
	public const SETTINGS = 'settings';
	public const SETTINGS_ASYNC_WORKERS = 'settings.async-workers';
	public const SETTINGS_ENABLE_DEV_BUILDS = 'settings.enable-dev-builds';
	public const SETTINGS_ENABLE_PROFILING = 'settings.enable-profiling';
	public const SETTINGS_FORCE_LANGUAGE = 'settings.force-language';
	public const SETTINGS_PROFILE_REPORT_TRIGGER = 'settings.profile-report-trigger';
	public const SETTINGS_SHUTDOWN_MESSAGE = 'settings.shutdown-message';
	public const TICKS_PER = 'ticks-per';
	public const TICKS_PER_AUTOSAVE = 'ticks-per.autosave';
}
